export default {
  container: {
    backgroundColor: "#1E1E1E",
    flex: 1,
  },
  main_titles: {
    fontSize: 26,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    marginTop: 55,
  },
  header_style: {
    backgroundColor: "#1E1E1E",
    height: 150,
    borderBottomLeftRadius: 50,
  },
  card_style: {
    borderRadius: 20,
    padding: 10,
    backgroundColor: "#696767",
    borderWidth: 0,
  },
  fav_card_style: {
    borderRadius: 20,
    padding: 10,
    backgroundColor: "#696767",
    borderWidth: 2,
    borderColor: "#0011A6",
  },
  list_item_style: {
    backgroundColor: "#696767",
    borderRadius: 15,
    height: 200,
    padding: 0,
  },
  edit_card_style: {
    borderRadius: 20,
    height: "420",
    backgroundColor: "#696767",
    borderWidth: 0,
  },
  list_edit_card_styles: {
    borderRadius: 20,
    height: "100%",
    backgroundColor: "#696767",
    borderWidth: 0,
  },
  card_titles: {
    color: "white",
    fontSize: 23,
    fontWeight: "bold",
  },
  card_subtitles: {
    color: "white",
    fontSize: 12,
    fontStyle: "italic",
    padding: 2,
  },
  round_buttons: {
    borderRadius: 100,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0011A6",
    margin: 2,
  },
  tiny_round_buttons: {
    borderRadius: 100,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0011A6",
    margin: 2,
  },

  reserva_button: {
    margin: 2,
    borderRadius: 20,
    width: 160,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0011A6",
  },
  button_text: {
    fontSize: 17,
    fontWeight: "bold",
    color: "white",
  },
  card_container: {
    flex: 1,
    padding: 10,
  },
  image_container: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  avatar_image: {
    borderRadius: 20,
    marginBottom: 10,
  },
  avatar_image_display: {
    width: 70,
    height: 70,
    marginRight: 10,
    borderRadius: 10,
  },
  edit_titles: {
    fontStyle: "italic",
    fontSize: 18,
    marginLeft: 10,
    color: "white",
    marginBottom: 2,
  },
  selected_image: {
    backgroundColor: "rgba(80,94,104,0)",
  },
  input: {
    height: 45,
    width: 320,
    marginBottom: 10,
    borderRadius: 20,
    textAlign: "center",
    fontSize: 20,
    fontStyle: "italic",
    backgroundColor: "white",
  },
  tiny_input: {
    height: 45,
    width: 155,
    marginBottom: 10,
    borderRadius: 20,
    textAlign: "center",
    fontSize: 20,
    fontStyle: "italic",
    backgroundColor: "white",
  },
  button_pick: {
    backgroundColor: "#fff",
    borderRadius: 20,
    width: 165,
    height: 50,
    marginBottom: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  tiny_button_pick: {
    backgroundColor: "#fff",
    borderRadius: 20,
    width: 140,
    height: 50,
    marginBottom: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  big_button: {
    margin: 2,
    borderRadius: 20,
    width: 155,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0011A6",
  },
  create_titles: {
    fontSize: 20,
    fontStyle: "italic",
    color: "black",
    opacity: "0.7",
    padding: 5,
  },
  picker_icons: {
    color: "black",
    opacity: "0.7",
  },
  button_titles: {
    fontWeight: "bold",
    color: "white",
    fontSize: 22,
  },
};
